apiVersion: v1
kind: Pod
metadata:
  name: app-with-secret
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secret
