apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: exam-netpol
  namespace: exam-ns
spec:
  podSelector:
    matchLabels:
      app: web
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: exam
    ports:
    - protocol: TCP
      port: 80 
