apiVersion: v1
kind: Pod
metadata:
  labels:
    app: exam
  name: exam-nginx-1
  namespace: exam-ns
spec:
  containers:
  - image: nginx:1.27
    name: exam-nginx-1
    resources:
      limits:
        memory: "128Mi"
        cpu: "200m"
    envFrom:
    - configMapRef:
        name: exam-config
    - secretRef:
        name: exam-secret
---
apiVersion: v1
kind: ConfigMap
metadata: 
  name: exam-config
  namespace: exam-ns
data: 
  APP_ENV: "production"
  APP_PORT: "8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: exam-secret
  namespace: exam-ns
type: Opaque
stringData:
  DB_PASSWORD: "secret123"

