apiVersion: v1
kind: Namespace
metadata:
  name: team-frontend
  labels:
    team: frontend
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-backend
  labels:
    team: backend
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-devops
  labels:
    team: devops
    env: production
